### ISSUE TITLE
(consult-omni-apps) Apps cannot write to stderr after launching

### ISSUE THREAD

**Issue by Dev380** [armindarvish/consult-omni#25]
**Describe the bug**

Some apps (I tested using armcord, which uses electron) expect stderr to be open after launching. However, consult-omni currently keeps it closed, resulting in an error with these apps.

**To Reproduce**
1. Open `consult-omni-apps`
2. Launch armcord, discord or similar electron app
3. See error

**Expected behavior**

The app should launch normally as would be expected when using `gtk-launch appname.desktop` from a terminal.

**Screenshots**

![20240817_16h24m40s](https://github.com/user-attachments/assets/63d70f50-5d9e-4f09-b3c2-2ce55043bc32)

**Important Information:**
 - OS: Arch Linux
 - Emacs 30.0.50
 - Version of `consult`: 1.7
 - Installation: doom emacs's straight.el with standard configuration.
 - If there is an error message: N/A

**Comment by armindarvish** [comment]
This was resolved in #24, so closing it now!
